name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: proxmon
            name: proxmon-Linux-x86_64.tar.gz

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: proxmon
            name: proxmon-Darwin-x86_64.tar.gz

          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: proxmon
            name: proxmon-Darwin-aarch64.tar.gz

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: proxmon.exe
            name: proxmon-Windows-x86_64.zip

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.platform.target }}

      - name: Package as archive (Unix)
        if: matrix.platform.os != 'windows-latest'
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -

      - name: Package as archive (Windows)
        if: matrix.platform.os == 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -

      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.platform.name }} > ${{ matrix.platform.name }}.sha256

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            ${{ matrix.platform.name }}
            ${{ matrix.platform.name }}.sha256
          body: |
            ## Installation

            ### From Binary
            Download the appropriate binary for your platform, extract it, and move to your PATH.

            **macOS/Linux:**
            ```bash
            tar xzf proxmon-*.tar.gz
            chmod +x proxmon
            sudo mv proxmon /usr/local/bin/
            ```

            **Windows:**
            Extract the zip and add `proxmon.exe` to your PATH.

            ### From Source (with Cargo)
            ```bash
            cargo install proxmon
            ```

            ### From Git
            ```bash
            cargo install --git https://github.com/0xgoz/proxmon --tag ${{ github.ref_name }}
            ```

            ## What's New
            See the full changelog in [CHANGELOG.md](CHANGELOG.md)

            ---
            🎮 **Gotta manage 'em all!**

