name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            name: proxmon-darwin-x86_64.tar.gz

          - target: aarch64-apple-darwin
            os: macos-latest
            name: proxmon-darwin-aarch64.tar.gz

          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04  # Use older Ubuntu for better glibc compatibility
            name: proxmon-linux-x86_64.tar.gz

          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            name: proxmon-linux-x86_64-musl.tar.gz

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: proxmon-windows-x86_64.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl tools (Linux MUSL)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/proxmon

      - name: Create archive (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.name }} proxmon
          cd -

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd target/${{ matrix.target }}/release
          Compress-Archive -Path proxmon.exe -DestinationPath ../../../${{ matrix.name }}
          cd -

      - name: Generate SHA-256 checksum
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            shasum -a 256 ${{ matrix.name }} > ${{ matrix.name }}.sha256
          else
            sha256sum ${{ matrix.name }} > ${{ matrix.name }}.sha256
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.name }}
            ${{ matrix.name }}.sha256
          body: |
            ## Proxmon ${{ github.ref_name }}

            🎮 **Gotta manage 'em all!** - A blazingly fast terminal UI for Proxmox

            ### ✨ What's New in This Release

            - Auto-creates config file on first run - no manual setup needed!
            - Press 'a' to add your first Proxmox host interactively
            - Universal Linux MUSL build works on any distro

            ### 📦 Installation

            Download the appropriate binary for your platform below, extract it, and move it to your PATH.

            **macOS:**
            ```bash
            # Apple Silicon (M1/M2/M3)
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/proxmon-darwin-aarch64.tar.gz | tar xz

            # Intel
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/proxmon-darwin-x86_64.tar.gz | tar xz

            # Install
            chmod +x proxmon
            sudo mv proxmon /usr/local/bin/
            ```

            **Linux (Recommended - works on ANY distro!):**
            ```bash
            # MUSL build - statically linked, zero dependencies
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/proxmon-linux-x86_64-musl.tar.gz | tar xz
            chmod +x proxmon
            sudo mv proxmon /usr/local/bin/

            # Or standard glibc build (Ubuntu 20.04+, Debian 11+)
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/proxmon-linux-x86_64.tar.gz | tar xz
            chmod +x proxmon
            sudo mv proxmon /usr/local/bin/
            ```

            **Windows:**
            Download `proxmon-windows-x86_64.zip`, extract, and add to your PATH.

            ### 🦀 Alternative Installation

            If you have Rust/Cargo installed:
            ```bash
            cargo install proxmon
            ```

            ### ✅ Checksums

            SHA-256 checksums are provided for all binaries for verification.

            ### 🚀 First Run

            Just run `proxmon` - it will auto-create the config file!
            ```bash
            proxmon
            # Press 'a' to add your first Proxmox host
            ```

            Config is saved to `~/.config/proxmon/config.yml`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
